"""Workflow orchestration package for UI-facing flows."""

from souschef.orchestrators.bash import (
    convert_bash_content_to_ansible,
    generate_ansible_role_from_bash,
    parse_bash_script_content,
)
from souschef.orchestrators.chef import (
    analyse_cookbook_dependencies,
    assess_single_cookbook_with_ai,
    calculate_activity_breakdown,
    orchestrate_calculate_file_fingerprint,
    orchestrate_conversion_analysis,
    orchestrate_cookbook_metadata_parsing,
    orchestrate_generate_playbook_from_recipe,
    orchestrate_generate_playbook_from_recipe_with_ai,
    orchestrate_get_blob_storage,
    orchestrate_get_storage_manager,
    orchestrate_repository_generation,
    orchestrate_template_conversion,
    parse_chef_migration_assessment,
)
from souschef.orchestrators.powershell import (
    analyze_powershell_migration_fidelity,
    convert_powershell_content_to_ansible,
    generate_ansible_requirements,
    generate_powershell_awx_job_template,
    generate_powershell_role_structure,
    generate_windows_group_vars,
    generate_windows_inventory,
    parse_powershell_content,
)
from souschef.orchestrators.puppet import (
    convert_puppet_manifest_to_ansible,
    convert_puppet_manifest_to_ansible_with_ai,
    convert_puppet_module_to_ansible,
    convert_puppet_module_to_ansible_with_ai,
    get_puppet_ansible_module_map,
    parse_puppet_manifest,
    parse_puppet_module,
)
from souschef.orchestrators.salt import (
    assess_salt_complexity,
    convert_salt_directory_to_roles,
    convert_salt_sls_to_ansible,
    generate_salt_inventory,
    parse_salt_directory,
    parse_salt_pillar,
    parse_salt_sls,
    plan_salt_migration,
)

__all__ = [
    "analyse_cookbook_dependencies",
    "analyze_powershell_migration_fidelity",
    "assess_salt_complexity",
    "assess_single_cookbook_with_ai",
    "calculate_activity_breakdown",
    "convert_bash_content_to_ansible",
    "convert_powershell_content_to_ansible",
    "convert_puppet_manifest_to_ansible",
    "convert_puppet_manifest_to_ansible_with_ai",
    "convert_puppet_module_to_ansible",
    "convert_puppet_module_to_ansible_with_ai",
    "convert_salt_directory_to_roles",
    "convert_salt_sls_to_ansible",
    "generate_ansible_requirements",
    "generate_ansible_role_from_bash",
    "generate_powershell_awx_job_template",
    "generate_powershell_role_structure",
    "generate_salt_inventory",
    "generate_windows_group_vars",
    "generate_windows_inventory",
    "get_puppet_ansible_module_map",
    "orchestrate_calculate_file_fingerprint",
    "orchestrate_conversion_analysis",
    "orchestrate_cookbook_metadata_parsing",
    "orchestrate_generate_playbook_from_recipe",
    "orchestrate_generate_playbook_from_recipe_with_ai",
    "orchestrate_get_blob_storage",
    "orchestrate_get_storage_manager",
    "orchestrate_repository_generation",
    "orchestrate_template_conversion",
    "parse_bash_script_content",
    "parse_chef_migration_assessment",
    "parse_powershell_content",
    "parse_puppet_manifest",
    "parse_puppet_module",
    "parse_salt_directory",
    "parse_salt_pillar",
    "parse_salt_sls",
    "plan_salt_migration",
]
