#!/usr/bin/env python3
"""Quick test to verify templates are included in archive."""

import io
import zipfile
from collections import defaultdict
from pathlib import Path

from souschef.converters.template import convert_cookbook_templates

# Test cookbook path
cookbook_path = "osl-openstack-0.0.5"
cookbook_name = "osl-packstack"

# Step 1: Convert templates
template_results = convert_cookbook_templates(cookbook_path)

# Step 2: Collect template data (mimicking UI code)
converted_templates = []
if template_results.get("success"):
    for template_result in template_results.get("results", []):
        if template_result["success"]:
            converted_templates.append(
                {
                    "cookbook_name": cookbook_name,
                    "template_content": template_result["jinja2_content"],
                    "template_file": Path(template_result["jinja2_file"]).name,
                    "original_file": Path(template_result["original_file"]).name,
                    "variables": template_result["variables"],
                }
            )

# Step 3: Create archive (mimicking _create_playbook_archive)
zip_buffer = io.BytesIO()

with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
    # Add templates
    for template in converted_templates:
        cb_name = template["cookbook_name"]
        template_filename = f"{cb_name}/templates/{template['template_file']}"
        zip_file.writestr(template_filename, template["template_content"])

    # Add README
    by_cookbook_templates = defaultdict(list)
    for template in converted_templates:
        by_cookbook_templates[template["cookbook_name"]].append(template)

    readme_content = f"""# Ansible Playbooks Generated by SousChef

This archive contains {len(converted_templates)} templates from 1 cookbook.

## Contents:
"""

    for cb_name, cb_templates in sorted(by_cookbook_templates.items()):
        readme_content += f"\n### {cb_name}/ ({len(cb_templates)} templates)\n"
        readme_content += "  - templates/\n"
        for template in cb_templates:
            readme_content += (
                f"    - {template['template_file']} "
                f"(from {template['original_file']})\n"
            )

    zip_file.writestr("README.md", readme_content)

# Step 4: Verify archive contents
zip_buffer.seek(0)
with zipfile.ZipFile(zip_buffer, "r") as zip_file:
    file_list = zip_file.namelist()
    # Verify templates are in archive (validates correctness)
    assert any("/templates/" in f for f in file_list)  # lgtm [py/unused-local-variable]

    # Save test archive
    Path("test_archive.zip").write_bytes(zip_buffer.getvalue())
